services:
  - name: invoice-backend
    image: koyeb/app
    type: Web Service
    env:
      - key: PORT
        value: "8000"
      - key: NODE_ENV
        value: "production"
      - key: MONGODB_URI
        secret: true
      - key: JWT_SECRET
        secret: true
      - key: TWILIO_ACCOUNT_SID
        secret: true
      - key: TWILIO_AUTH_TOKEN
        secret: true
    regions:
      - fra
    ports:
      - port: 8000
        http:
          paths:
            - /
    build:
      type: dockerfile
      dockerfile: |
        FROM node:20.15.0
        
        # Set working directory for the project
        WORKDIR /workspace
        
        # Copy the entire project
        COPY . .
        
        # Install and build frontend
        WORKDIR /workspace/FrontEnd
        RUN npm install
        RUN npm run build
        
        # Install backend dependencies and setup
        WORKDIR /workspace/BackEnd
        RUN npm install
        RUN mkdir -p public
        RUN cp -r ../FrontEnd/dist/* public/
        
        ENV NODE_ENV=production
        EXPOSE 8000
        CMD ["npm", "start"]
