services:
  - name: invoice-backend
    image: koyeb/app
    type: Web Service
    env:
      - key: PORT
        value: "8000"
      - key: NODE_ENV
        value: "production"
      - key: MONGODB_URI
        secret: true
      - key: JWT_SECRET
        secret: true
      - key: TWILIO_ACCOUNT_SID
        secret: true
      - key: TWILIO_AUTH_TOKEN
        secret: true
    regions:
      - fra
    ports:
      - port: 8000
        http:
          paths:
            - /
    build:
      type: dockerfile
      dockerfile: |
        FROM node:20.15.0
        WORKDIR /app
        
        # Copy backend files
        COPY BackEnd/package*.json ./
        RUN npm install
        COPY BackEnd/ .
        
        # Copy frontend files and build
        COPY FrontEnd/ ../frontend/
        WORKDIR /frontend
        RUN npm install
        RUN npm run build
        
        # Move frontend build to backend static directory
        WORKDIR /app
        RUN mkdir -p public
        RUN cp -r ../frontend/dist/* public/
        
        ENV NODE_ENV=production
        EXPOSE 8000
        CMD ["npm", "start"]
